# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Eddy Luten
subtitle: Blogging like it's 2006!
email: eluten@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Eddy Luten's personal blog with posts of dubious quality since 2006
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luten.dev" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/
breadcrumbs: true
excerpt_separator: <!--more-->
search: true
timezone: America/Chicago
paginate: 10

twitter:
  username: EddyLuten

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-36CTYKX5DC"

author:
  name     : "Eddy Luten"
  avatar   : "/images/hera-and-me.png"
  bio      : "Is typing<span id='tripdot' />"
  # location : "USA"
  email    : eluten@pm.me
  github   : EddyLuten
  linkedin : eddyluten
  bluesky  : luten.dev

footer:
  links:
    - label: "🦋 Bluesky"
      icon: "none"
      url: "https://bsky.app/profile/luten.dev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EddyLuten"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
date_format: "%Y-%m-%d"
locale: "en-US"
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-target-blank
  - jekyll-include-cache

tag_archive:
  type: jekyll-archives
  path: /tags/

category_archive:
  type: jekyll-archives
  path: /categories/

jekyll-archives:
  enabled:
    - categories
    - year
    - tags
  layouts:
    year: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    year: '/years/:year/'
    tag: /tags/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
